### ISSUE TITLE
Retro-bit Metal Storm Corrupted Graphics

### ISSUE THREAD

**Issue by BigPrimeNumbers** [analoguejb/Analogue-Nt-Mini-Noir-JB#7]
When playing Retro-bit's re-release of Metal Storm on JBv6.7, the graphics are corrupted. The game plays correctly with official v1.3 firmware.

**Comment by Cheesemeister3k** [comment]
Playing the original North American cartridge on jailbreak firmware 6.7, no incorrect graphics appeared to be displayed through stage 3-2.

**Comment by BigPrimeNumbers** [comment]
> Playing the original North American cartridge on jailbreak firmware 6.7, no incorrect graphics appeared to be displayed through stage 3-2.

I unplugged my unit from power and plugged it back in, and that seems to have fixed the issue. Not sure what happened - I had just freshly installed v6.7 with the cart inserted, so maybe something weird happened while flashing. Seems okay now.
